spring:
  data.neo4j:
    username: neo4j
    password: cloudinfantry
    profiles:
        active: @spring.profiles.active@

jwt-generation-properties:
  key-id: "0"
  issuer: "cloud-infantry"
  algorithm: "RS256"
  secret-key: "-----BEGIN PRIVATE KEY-----
               MIIJRAIBADANBgkqhkiG9w0BAQEFAASCCS4wggkqAgEAAoICAQDDqSlLsH0Olx2D
               wlve8hNER+5ff3S7say3EqmUqePldSmqEfML0nq3C5garua1F5BxM1mRTYKdHyIT
               1Gwxji6WGCJDIjGGoi7RM0FVNfZm1meb5mL1nUHpRlJHwS5WR30EwsbXkyzTfFv1
               SzMbRhzFS7SMa00ulR+q8NJ4jRmCM5nkSHvCbCi4MT8RMmRVaCVWrzwoQmdGMCvO
               AsHPI9ap/1+G3Fvu6iEOJa/17WaoUN7fNckIvzkpuw/4uKBQGH8tFhG29XR+45V3
               CLWna5gMKgviKRK6PbBH+asMrAXYrEfDCcO+us5Gnm3jDycZlxOQytHgxVN6ubWj
               Shn+YrkAjLjBzERGSzY9yXm+07jddMaYEmtCk3DvKd8LnEdGEotxpfsvgmvzPYJH
               Na9qhakbMNkfSEuiEaZhpAfAObwIvp3A/Yql5aukbdOEG0Fa6YjwH8H3OXpecFiG
               0cUhuB76Zaw8U05+8fuT8QrvHoOivhrmE0AsXW8661r6XJ3bmzn1DA0FK09rP0NV
               Tqa7m9Brd78AeUYIbWnbMyiKEN8bcC3c3YitqMBblfBqINGah4NnV3fRKCc0mD1N
               BlYmxfYq7oIc8ym2iG1n5T5PVhlzvPySD7KBEWt6Qk/UkYeV1O5BB8936Qoxcjx5
               wo3QVkUYLFzUt0+PkL0JMH56+EDC+QIDAQABAoICAQCyScSNacaqstx8IXChmKgh
               wgHeF0ABgAdH0sOf6ab2gWpzxGNZ1HNptDDnr5QeU9iUrhvhoWVxUts0go4MIekl
               b9xYnCHQ8pwCmNfhk4hxcNF8Z9SoxqE2tZNoOwnEKOQsoGecLEnedCU/QUTSh3LT
               /QYKJgRwfAYdN9AxdTFXSTnjoIDVSsVYAdfcDbULdhkAAjGo5clBVce0syJzY87J
               nSAovUcwTzvLrl/GkorGuNo9Pr9vLwAhnIkTNPkvwwKvzLpboxKCRVL+4nrUkeA8
               xVuKu66K8oddLo3EwEObinDhslYhyAsKonazPi18zgNQHuBcFrLY07xFjNJe0QqN
               cumylsK6/bhn7UppP0PMFVojJUez4R6XBpdztvHVAy+J9h0ng5jp5Z2JJEt7HtWx
               QYeBM3ZW+XspL9ALpRdWEQFHhK3C7JaeLhzm+0ELRacPFj/zDRpWRqKbR7JQeFH7
               athwRvXVm4b+N5plLAa5RhiJyNJjj8z3x+EBuSmxxURNDRcShg1+jIIeBKzRMpNY
               HJ9GNJp+WpCB34c3PaaYleB9KE8iPGsb1EW6ry+9Y4EDbLwskJ5nguQ84oPX0uU1
               JKY1qunL+Vpwl6rR3TcnQgW85rDGrBOI0vrKAu78jVYg/Xje+KswLSbmB5ls9/VN
               LuNH7zUtcbc18/SSvcEw2QKCAQEA7xMGn2QtG2MfGn78z4VKKQy90bM248+sECK8
               sPpOjjuZIw3YeyWw44GFyfeDRerTgQVdpC8eROE9qpOJgQszqIt0hvTfneaNyIug
               woZTZeUHqsnf2R/301e3SLc9Xv/i8j+QU/THRLKXuaIvkhc74raR0qa2kAh+P1Mt
               krPxSicX4t4LzZ+SP5iIgvLd4yU6/3IwRXzepqyEIGYPW79b1rm2LQl+MWJi/2Rq
               340DNStoNetBd4/H+F9abTcGWC0uTwEvUtkc+4hnNiCjpQZ8xez4fIYKkGYXWxLw
               UCWoP1Awb6K/cYcSvLC4meFUxQ2ak1GuiuQnoybR7EJjso23wwKCAQEA0YNPZx50
               mM+1hUsHzG8hbt5MAp3SkKSP9ULlUxqArpYKrV7QQ8+elZv4I25ybGH3pZHh0FGp
               MLQnPtFivf5eCAWorm2eCvWGsygpNDCN7bhpuXfMa9PHxilQGHv31VEuDCN7iIcu
               VrKLeq8Op9Vy6qUsBxHVEClyJ6ra3at8mIjaU1tNKOhWMwvMvan7Mzn2ib3PZ8yL
               sPNIlWz60/+URCrO0JzFStjWsvzL1cC3t1BLIymiGA/+pR14ew8v1R5fFU7dje9u
               WfuIzp4w/oyzG7wSV1ko86zgfNLZRhXOFWMnbX7p/6kmIel3wgYm3vp5zISDji4M
               308Sxa1YdvjqkwKCAQEA1IOFD4pszjt+Gn9nGtDQ60x4Lz+vOzIPMQiv0mGuEqDH
               r3FPTahjZNhtpOpvtmbXO4kZhCieL3xI5KfhQuRCN0A/hPeHD0UyI2J6tG/TEnBU
               MGzino7cLPF76xd3Zkrv4Ya/NOIRf++BD3Ir9yDQCudfGHE5Ny9VidTWXeG2SsQV
               Z4UZ2N5Pklh0gHKC6rbditRmNF6bTG1txZ7zaAriCC1s0vvtQNjER2Fr3uvqPgkn
               yUYmG7GjgBTCvPJ8oUUINRJIjsyQBsdpd6Pr03XA0++hso80NMeLW1mqZJQUyrLt
               W06//pqi/TfZ4G98eu1syieBj9TfpxeK4wjgtodjIQKCAQEAl9+a6IJQPRGcYPJh
               xdTtJGQqL19eaxGPdVe3ywUUMPp85O4tBGr1Zzg3qN+APIbLsQ7N5We8wJxnMocw
               D8/bM+9+NmspvIH80dQUAkwMJj2fDh4EZkmPsFr0P7tljRGa0pvKCc8MTTaCGz3Y
               3trAwc1X3AwWKfARWyXkH/oWiK/zq6csiLHbAofUM8yLVrf2uiSIu5Kv1GaWwBLO
               xGyperyZTOnHrpj/EaJk1B8uTcj7npKoeM7nZaO2WWZJ4zBv9o9D1YaxtLK8miJc
               G7m8gCdWGFF+eR1hYbqqW76ktCY7R4lPcM+Z381QzaoN9WcWcaXBg4hoNlwonHkq
               /psz1wKCAQAzqtmTcm+WYyMn84/xuLfb4cQ/fdl8Ffe2Awuf+Q79XmvK4RWeIObK
               kl+O7dX6/zSZGbtprIROWk8M3noht4xF42HaCtAKsZ59y/0iawUZ2egMMw+uPTiZ
               taPWwGJNWc86lYchD+pjX7H4zDSD+q4ZRBOxES3IxCUzftuCtTpiuSQrqMpnrxMa
               okx0/Wg/6Sl0oYhleIa8rGBUac+qFfSw+i/rCmQXSDj1/qC3e9FubV9I7wznyHaG
               zELJUYLgXGq9Xob9ooHgSzHcBsnFefE7GzPxUEA7fqv5Lt98wYQtx+WhU03Cj+tQ
               XJf84+hojunwqBAngdZuZ7EyLJ3TzDUP
               -----END PRIVATE KEY-----
               "
jwt-extraction-config:
  public-key: "-----BEGIN PUBLIC KEY-----
    MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAw6kpS7B9Dpcdg8Jb3vIT
    REfuX390u7GstxKplKnj5XUpqhHzC9J6twuYGq7mtReQcTNZkU2CnR8iE9RsMY4u
    lhgiQyIxhqIu0TNBVTX2ZtZnm+Zi9Z1B6UZSR8EuVkd9BMLG15Ms03xb9UszG0Yc
    xUu0jGtNLpUfqvDSeI0ZgjOZ5Eh7wmwouDE/ETJkVWglVq88KEJnRjArzgLBzyPW
    qf9fhtxb7uohDiWv9e1mqFDe3zXJCL85KbsP+LigUBh/LRYRtvV0fuOVdwi1p2uY
    DCoL4ikSuj2wR/mrDKwF2KxHwwnDvrrORp5t4w8nGZcTkMrR4MVTerm1o0oZ/mK5
    AIy4wcxERks2Pcl5vtO43XTGmBJrQpNw7ynfC5xHRhKLcaX7L4Jr8z2CRzWvaoWp
    GzDZH0hLohGmYaQHwDm8CL6dwP2KpeWrpG3ThBtBWumI8B/B9zl6XnBYhtHFIbge
    +mWsPFNOfvH7k/EK7x6Dor4a5hNALF1vOuta+lyd25s59QwNBStPaz9DVU6mu5vQ
    a3e/AHlGCG1p2zMoihDfG3At3N2IrajAW5XwaiDRmoeDZ1d30SgnNJg9TQZWJsX2
    Ku6CHPMptohtZ+U+T1YZc7z8kg+ygRFrekJP1JGHldTuQQfPd+kKMXI8ecKN0FZF
    GCxc1LdPj5C9CTB+evhAwvkCAwEAAQ==
    -----END PUBLIC KEY-----
    "